### ISSUE TITLE
Compile JSX before publishing to NPM registry

### ISSUE THREAD

**Issue by menelaos** [andreypopp/react-fa#1]
Would it be possible to compile Icon.js before publishing it to the NPM registry? That way the code would be valid JavaScript and wouldn't require the user to have an additional build step.

**Comment by stubbornella** [comment]
We'd be interested in this too, and willing to create a PR if you are open to it?

**Comment by andreypopp** [comment]
@stubbornella sure, @KyleAMathews did a similar [PR](https://github.com/andreypopp/react-time/pull/9) to [andreypopp/react-time](https://github.com/andreypopp/react-time)

**Comment by stubbornella** [comment]
Super, I think we should get to it in the next week given our other priorities.

**Comment by andreypopp** [comment]
@stubbornella awesome, looking forward to the PR!
