### ISSUE TITLE
React 0.14

### ISSUE THREAD

**Issue by jarib** [andreypopp/react-fa#13]
The [first beta of React 14](http://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html) is out, but react-fa depends on`< 0.14.0` and prevents me from trying it out.

Any reason for this?

**Comment by andreypopp** [comment]
No reason, just to be sure we are safe from possible breakages.

**Comment by andreypopp** [comment]
4.0.0 supports React 0.14
