### ISSUE TITLE
Pass function to name instead of string

### ISSUE THREAD

**Issue by MinThaMie** [andreypopp/react-fa#17]
I want my icons to match the state of the window they are in. So I wrote a function to get the right Icon, but if I put that button in the name field like this: `<Icon name= {this._getIcon()}`. This results in a ProtoType error: Warning: Failed propType: Required prop `name` was not specified in `Icon`.

It would be a great enhancement if you could pass and object like this without it giving a warning.

**Comment by andreypopp** [comment]
If you need to alter icon based on your app's state you can just re-render the `<Icon />` component:

```
import React from 'react'
import Icon from 'react-fa'

class App extends React.Component {

  constructor(props) {
    super(props)
    this.state = {flip: false}
  }

  render() {
    return <Icon onClick={this.onClick.bind(this)} name={flip ? 'pencil' : 'remove'} />
  }

 onClick() {
   this.setState({flip: !this.state.flip})
 }
}
```

**Comment by MinThaMie** [comment]
Okay, but why is my method wrong? Cause that would allow for multiple states/phases where ? : doesnt do that

**Comment by andreypopp** [comment]
Sorry, I misread your code example and replied to issue's title which states that you want to a function to the `<Icon />` component.

In your code sample:

```
<Icon name= {this._getIcon()} />
```

you don't pass a function but instead call a function and passes its result into component.

That's fine and supported. But you get the warning:

```
ProtoType error: Warning: Failed propType: Required prop name was not specified in Icon.
```

Which shows that your function doesn't return any string constant which is required to be passed to `<Icon />`. Can you show your `_getIcon()` method source code?

**Comment by MinThaMie** [comment]
```
_getIcon(){
        if (this.state.opened) {
            let customIcon ="caret-left";
            return customIcon ;
        }
        else{
            let customIcon ="caret-right";
            return customIcon;

        }
    }
```
