### ISSUE TITLE
Tag name option

### ISSUE THREAD

**Issue by Va1** [andreypopp/react-fa#19]
Hey!

Currently, icon renders with "span" tag ([look here](https://github.com/andreypopp/react-fa/blob/master/src/Icon.js#L60)), but I'd like to use "i" tag here. Can't we make a tag prop on the Icon component? I'd like to submit a PR if it is fine with you.

**Comment by andreypopp** [comment]
What's the use case, I mean what's the reason to use `<i />` instead of `<span />`?

**Comment by Va1** [comment]
Disregard that, I cook socks.
