### ISSUE TITLE
Exception when use new babel-loader@6.2.3

### ISSUE THREAD

**Issue by TeaTimeForever** [andreypopp/react-fa#29]
ERROR in ./~/react-fa/lib/index.js
Module build failed: ReferenceError: [BABEL] /path/to/project/node_modules/react-fa/lib/index.js: Unknown option: /path/to/project/node_modules/react-fa/.babelrc.stage

**Comment by andreypopp** [comment]
Should be fixed with 4.1.1. But FYI you don't need to process `react-fa` package with Babel as it is shipped as compiled ES5 code.
