### ISSUE TITLE
Default to <i> instead of <span>

### ISSUE THREAD

**Issue by rymohr** [andreypopp/react-fa#30]
I'm curious why you chose to go with `<span>` as the default when font awesome uses `<i>` for all their examples?  Using `<i>` also makes styling icons a little cleaner (being able to use `i` instead of `.fa`).

![image](https://cloud.githubusercontent.com/assets/730211/13333696/582ddcc4-dbac-11e5-9823-287547647d2a.png)

**Comment by pierrecholhot** [comment]
@rymohr Well, I am not the developer, but `<i>` stands for `italic` not for `icon`. It seems semantically wrong to use this tag for an `icon`. IMHO it's like using the `<tt>` tag for a `Tooltip`..

**Comment by andreypopp** [comment]
@pierrecholhot yep!

**Comment by rymohr** [comment]
Thanks, I get that. I'm just confused by the deliberate decision to go against font awesome standards:

![image](https://cloud.githubusercontent.com/assets/730211/14868042/36ff0d66-0c67-11e6-89a7-0a3b2202efe7.png)

**Comment by M3lkior** [comment]
Unfortunatly, @rymohr remark is legitimate. i'm using FA in jQuery / Bootstrap application, with custom skin based on `<i>` markup.
I want to provide a React equivalent but using your component break my styles due to the use of `<span>` instead of `<i>`, too bad :/.
