### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by zachariahtimothy** [andreypopp/react-fa#4]
I am attempting to use this module with webpack and webpack dev server.  It did not work on my existing working project so I tried it in a sandbox new app and received the exact same errors.  When running webpack I receive the following for each font awesome file.  :

ERROR in ./~/react-fa/~/font-awesome/fonts/fontawesome-webfont.eot?v=4.3.0
Module parse failed: /Users/zachcurtis/_Projects/choiceRV/missionControlReact/node_modules/react-fa/node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.3.0 Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./~/react-fa/~/font-awesome/css/font-awesome.css 2:302-353

I also see this error for every file type:
ERROR in ./~/react-fa/~/font-awesome/css/font-awesome.css
Module build failed: Error: Cannot find module "../fonts/fontawesome-webfont.eot?v=4.3.0"
    at webpackMissingModule (eval at <anonymous> (/Users/zachcurtis/_Projects/choiceRV/missionControlReact/node_modules/css-loader/index.js!/Users/zachcurtis/_Projects/choiceRV/missionControlReact/node_modules/react-fa/node_modules/font-awesome/css/font-awesome.css:502:2), <anonymous>:2:367)

Any tips would be GREATLY appreciated.

**Comment by pughpugh** [comment]
I had a similar issue earlier. I would hazard a guess that it's due to the `v=4.3.0` on the end of the font path not matching the regexp in your webpack loader test.

I use..

```
{
  test: /\.(otf|eot|png|svg|ttf|woff|woff2)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
  loader: 'url?limit=8192'
}    
```

**Comment by zachariahtimothy** [comment]
That totally fixed that error! Thank you so much. Next issue is the font-awesome.css is not actually getting loaded. Any tips there?

**Comment by pughpugh** [comment]
Are you using the `ExtractTextPlugin` as per the README? Is so you will need to load the bundle.css in your html. If you remove it, the css will be bundled into your js bundle.

```
<link rel="stylesheet" href="assets/bundle.css">
```

**Comment by zachariahtimothy** [comment]
I cannot get bundle.css to load via HTML.  When I do I get all green on
terminal but no bundle.css file gets generated. If I add
require('styles.css') to my app component file, styles.css gets loaded and
the icon rendered in HTML but not the CSS for font awesome.  Strange
behavior to say the least.

Child extract-text-webpack-plugin:
                                     Asset    Size  Chunks       Chunk Names
      f7c2b4b747b1a225eb8dee034134a1b0.eot   60767
    97493d3f11c0a3bd5cbd959f5d19b699.woff2   56780
     d9ee23d59d0e0e727b51368b458a0bff.woff   71508
      706450d7bba6374ca02fe167d86685cb.ttf  122092
      2980083682e94d33a66eef2e7d612519.svg  313398
    chunk    {0}
/Users/zachcurtis/_Projects/choiceRV/missionControlReact/node_modules/extract-text-webpack-plugin
/Users/zachcurtis/_Projects/choiceRV/missionControlReact/node_modules/css-loader/index.js!/Users/zachcurtis/_Projects/choiceRV/missionControlReact/node_modules/react-fa/node_modules/font-awesome/css/font-awesome.css
33195 [rendered]
        [0] ./~/css-loader!./~/react-fa/~/font-awesome/css/font-awesome.css
32354 {0} [built]
        [1] ./~/css-loader/cssToString.js 352 {0} [built]
        [2]
./~/react-fa/~/font-awesome/fonts/fontawesome-webfont.eot?v=4.3.0 81 {0}
[built]
        [3] ./~/react-fa/~/font-awesome/fonts/fontawesome-webfont.eot 81
{0} [built]
        [4]
./~/react-fa/~/font-awesome/fonts/fontawesome-webfont.woff2?v=4.3.0 83 {0}
[built]
        [5]
./~/react-fa/~/font-awesome/fonts/fontawesome-webfont.woff?v=4.3.0 82 {0}
[built]
        [6]
./~/react-fa/~/font-awesome/fonts/fontawesome-webfont.ttf?v=4.3.0 81 {0}
[built]
        [7]
./~/react-fa/~/font-awesome/fonts/fontawesome-webfont.svg?v=4.3.0 81 {0}
[built]

---

Zach Curtis
P: 970.590.6383
E: zachariahtimothy@gmail.com
T: @zachariahCurtis https://twitter.com/#!/@zachariahCurtis
B: http://zachariahtimothy.wordpress.com/

**Comment by zachariahtimothy** [comment]
I ended up changing {loader: ExtractTextPlugin.extract('style-loader', 'css-loader')} to {loaders: ['style-loader', 'css-loader']} and it works great! Thanks!

**Comment by halt-hammerzeit** [comment]
I had this error and I fixed it by moving webpack "modules" section before webpack "plugins" section in the webpack.config.js file.

**Comment by catamphetamine** [comment]
I was having this error when in webpack configuration I had `loaders: [ExtractTextPlugin.extract(...)]` and didn't have this error when it was temporarily changed to `loader: ExtractTextPlugin.extract(...)`.
Seems to be a bug: loaders[] and loader should be interchangeable.
