### ISSUE TITLE
Font not loading with Webpack Dev Server

### ISSUE THREAD

**Issue by edenworky** [andreypopp/react-fa#42]
I can load it no problem, but the font doesn't load and it only shows squares instead of icons. Works properly when built and extracted.

My font loaders are the same as in the example.

**Comment by konstantin24121** [comment]
Try change your publicPath to absolute 

``` js
{
  output: {
    publicPath: "http://localhost:8080/", // Development server
    // publicPath: "http://example.com/", // Production
}
```

and here a question http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts/34133809#34133809

**Comment by edenworky** [comment]
Ohh, I see. I got it to work now. That can be misleading when trying to integrate the Webpack config in the README into an existing config. I'll put up a PR in a few minutes.

**Comment by andreypopp** [comment]
Glad you figured it out. Closing the issue as there's nothing actionable. Feel free to continue discussion.
