### ISSUE TITLE
CSS modules option?

### ISSUE THREAD

**Issue by wlingke** [andreypopp/react-fa#47]
I had a bit of trouble integrating this because I use css modules. Realized I had to not use css modules in webpack to load it since class names are just global names.

Any thought on changing it up to use CSS modules?

**Comment by solshark** [comment]
Same issue. Any solution?

**Comment by andreypopp** [comment]
You need to specify a loader for font-awesome CSS separately (w/o CSS modules enabled). Just use more specific `test` in loader config for that.

**Comment by patrickgordon** [comment]
I'd love to get an example on how to make this work. Been racking my brain for hours 😬
