### ISSUE TITLE
Mark repository as archived?

### ISSUE THREAD

**Issue by TomasHubelbauer** [andreypopp/react-fa#64]
Hi, it seems this repository is no longer actively maintained. I'm judging this by the fact that the last publish to NPM was two years ago. That's absolutely fine, however, I would like to request that you either mark the repository as archived or add a notice to the README on GitHub and NPM, as that would help people realize immediately. I only noticed after some icons from FA 5 I was using were not available. I have switched to https://github.com/FortAwesome/react-fontawesome which you could point people to as an alternative which is actively maintained.

**Comment by andreypopp** [comment]
Makes sense. I've deprecated the package on npm and mentioned official react-fontawesome package, don't want to archive the repo yet as it will make issues read only — I don't expect someone would want to maintain this but just in case will leave a communication channel open for some time

**Comment by TomasHubelbauer** [comment]
Good point about Github issues, I had no idea that was the case.
