### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by LynxDelli** [andreypopp/react-fa#7]
On build I have an error.

``` Script
events.js:72
        throw er; // Unhandled 'error' event
              ^
SyntaxError: Unexpected character '@'
```

I use it with gulp. Error occur just from adding 
FontAwesome = require('react-fa')

**Comment by andreypopp** [comment]
What's your build config?

**Comment by LynxDelli** [comment]
It's similar to following workflow - https://github.com/LynxDelli/gulp-workflow 
I also tried it inside gulp-workflow project and got the same error.

**Comment by andreypopp** [comment]
The entry point is meant to be used with webpack. If you want to use it
with browserify (as in gulp-wotkflow you linked to) then you need to
require react-fa/dist/Icon and load CSS and fonts yourself.
