### ISSUE TITLE
Example url-loader config misses get parameters and woff2 type

### ISSUE THREAD

**Issue by NochEinKamel** [andreypopp/react-fa#9]
Hi,

With the url-loader configuration in the readme I get a lot of build errors telling me "you may need an appropriate loader"

```
@ ./~/css-loader!./~/react-fa/~/font-awesome/css/font-awesome.css 2:627-678
ERROR in ./~/react-fa/~/font-awesome/fonts/fontawesome-webfont.svg?v=4.3.0
You may need an appropriate loader to handle this file type.
| <?xml version="1.0" standalone="no"?>
```

Apparently the test fails because of the get parameter.
Also there is a woff2 icon-font which is missing in the test.

Adding woff2 and some regex for the parameters fixes the errors

```
{
    test: /\.(otf|eot|svg|ttf|woff|woff2)(\?.+)?$/,
    loader: 'url-loader?limit=8192'
}
```

Cheers

**Comment by Rodeoclash** [comment]
I got this as well, thanks for the fix. Looks like its just needs a PR on the README.md, I can hande this if you want?

**Comment by tomchentw** [comment]
Thanks for the fix!

**Comment by andreypopp** [comment]
That's fixed now
